= Object Generator
v{display-version}, January 22nd, 2016
:toc: right
:sectlinks:
:sectanchors:
:numbered:
:source-highlighter: highlightjs
:icons: font
:sampledir: ../resources/conf/sample

== Introduction
Object Generator (OG) is an HTTP object storage load tool designed for system
level stress, stability, and performance test. OG supports several common
object storage APIs including S3 and OpenStack Swift.

== Installation

=== Minimum Requirements
|===
|Component|Configuration

|CPU
|Dual Core

|Memory
|4GB system; 2GB available

|Free Disk Space
|20GB for logging

|Operating System
|Modern Linux OS*

|Java Version
|Java 7
|===

NOTE: OG has been tested on Ubuntu 14.04, but any modern linux OS should work.

=== Distribution
OG is distributed as a _tar.gz_ archive. To install, simply unpack the archive
in a directory of your choice.

[source, bash, subs="attributes"]
----
~$ tar -zxf og-{display-version}.tar.gz
----

== Project Layout
The OG project consists of the following files and directories:

[source, bash]
----
~$ tree
├── conf // <1>
│   ├── object-file-log4j2.xml
│   ├── og-log4j2.xml // <2>
│   └── sample // <3>
├── docs
│   └── userguide.html <4>
├── lib // <5>
├── log // <6>
├── object // <7>
├── object-file // <8>
└── og // <9>
----
<1> Configuration directory. Includes logging configuration and sample test configurations
<2> OG logging configuration
<3> Sample test configurations
<4> This user guide
<5> Third party library dependencies
<6> Default log location
<7> Default object file location
<8> Auxiliary object file management script
<9> Primary OG load driver script

=== Invocation
OG is a command line load tool which is controlled via the _og_ launch
script.

[source, bash]
----
$ ./og --help
Usage: og [<og_config>] [-v|--version] [-h|--help]
  [<og_config>]
        A relative or absolute path to an og json configuration file

  [-v|--version]
        Prints the og version and exits

  [-h|--help]
        Prints this help and exits
----

== Configuration
OG is configured via a json formatted test configuration file. This file
controls which object storage API to use, request and file size mix, the type
of concurrency to use, and much more.

=== Storage
OG supports the following Storage APIs:

|===
|Storage API

|S3

|OpenStack Swift

|Cleversafe SOH

|WebDAV
|===

Write, Read, and Delete operations are supported for each of the supported
Storage APIs. Storage API is configured via the _api_ key:

.S3 API Example
[source, json]
----
"api": "s3"
----

=== Authentication
OG supports the following authentication configurations:

|===
|Authentication

|Anonymous

|Basic Auth

|AWS Auth V2

|AWS Auth V4

|Keystone
|===

Authentication is configured via an _authentication_ block of the test
configuration:

[source, json]
----
"authentication": {}
----

==== Anonymous
Anonymous authentication is the default authentication configuration. It
is configured by omitting the _authentication_ block from the test
configuration.

==== Basic Auth
Basic authentication uses base64 encoding to encode username and password
credentials into an authorization request header that is sent to the target
server.

.Basic Auth Example
[source, json]
----
"authentication": {
  "type": "basic",
  "username": "my_user",
  "password": "my_password"
}
----

==== AWS Auth V2
AWS Auth V2 authentication is an S3 authentication scheme which uses several
elements of an object storage request to generate a request signature.

AWS Auth uses an access key and secret key for credentials, which map onto OG
_username_ and _password_ keys, respectively.

.AWS Auth V2 Example
[source, json]
----
"authentication": {
  "type": "awsv2",
  "username": "AKIAIOSFODNN74SFNMK",
  "password": "nJalrUUFklNEMI/K7MDENG/gPwRfiCYXY73DER"
}
----

==== AWS Auth V4
AWS Auth V4 authentication is an S3 authentication scheme which uses several
elements of an object storage request to generate a request signature.

AWS Auth uses an access key and secret key for credentials, which map onto OG
_username_ and _password_ keys, respectively.

With AWS Auth V4, the body of the request is included in the signing process.
AWS Auth V4 requests can either sign the entire request body up front, which
requires reading the entire contents first, or sign the body in chunks as the
request is sent. Chunked signing and chunk size are configured via
_aws_chunked_ and _aws_chunk_size_, respectively. Both configurations are
optional.

NOTE: For more information about AWS V4 signing, see: http://docs.aws.amazon.com/AmazonS3/latest/dev/RESTAuthentication.html[Signing and Authenticating REST Requests]

Because the signing process for V4 requests is CPU intensive, OG additionally
provides an optional mechanism for caching signatures for request bodies. This
reduces the CPU load on the load tool, which in turn reduces the risk of the
load tool as a performance bottleneck when executing V4 performance tests. To
enable caching, OG must be configured to write objects with all zeroes for data
(See Data section) so that the signatures are cacheable. Then, to enable the
cache, configure the cache size via _aws_cache_size_.

.AWS Auth V4 Example
[source, json]
----
"authentication": {
  "type": "awsv4",
  "username": "AKIAIOSFODNN74SFNMK",
  "password": "nJalrUUFklNEMI/K7MDENG/gPwRfiCYXY73DER",
  "aws_chunked": true,
  "aws_chunk_size": 8000,
  "aws_cache_size": 1000 
}
----

==== Keystone
Keystone authentication is an OpenStack Swift authentication scheme which
typically relies on an external Keystone server to generate an authentication
token for use by object storage requests. Keystone support in OG does not
include token lookup via an external Keystone server. Rather, OG requires a
keystone token be manually generated prior to test start.

.Keystone Example
[source, json]
----
"authentication": {
  "type": "keystone",
  "keystone_token": "7fe2cd9ee6384a1894a43878d3e52daf"
}
----

=== Host
Host is the target server that the OG load tool communicates with to execute
object storage requests. A host can be either a host name or an IPv4 IP
address. OG supports single and multiple host configurations. For multiple
hosts, OG supports selection of a host for a given request via round robin,
random, or weighted random configurations. Host(s) are configured via the
_host_ key.

.Single Host Example
[source, json]
----
"host": "127.0.0.1"
----

.Multiple Host Round Robin Example
[source, json]
----
"host": {
  "selection": "roundrobin",
  "choices": ["127.0.0.1", "s3.amazonaws.com"]
}
----

.Multiple Host Random Example
[source, json]
----
"host": {
  "selection": "random",
  "choices": ["127.0.0.1", "s3.amazonaws.com"]
}
----

.Multiple Host Weighted Random Example
[source, json]
----
"host": {
  "selection": "random",
  "choices": [
    {
      "choice": "127.0.0.1",
      "weight": 80.0
    },
    {
      "choice": "s3.amazonaws.com",
      "weight": 20.0
    }
  ]
}
----

=== Port
OG supports configuring the port that object storage requests are executed
against. Port configuration applies to all configured hosts. Port is
configured via the _port_ key.

.Port Example
[source, json]
----
"port": "8080"
----

=== URI Root
OG supports configuring the root URI path that the object storage API is
located at. URI Root is configured via the _uri_root_ key, and the default
value is to root the configured Storage API at _/<api>/_. For example,
request URIs for S3 requests using the default _uri_root_ would take the form: 

[source, bash]
----
/s3/<container>/<object>
----

.URI Root Alternate Example
[source, json]
----
"uri_root": "/"
----

=== Virtual Host
Some Object Storage implementations support virtual host addressing, which is
a way to express containers as virtual sub-domains. OG supports this
configuration via the _virtual_host_ key. The default configuration is false,
which means that object storage request URIs are of the form: 

[source, bash]
----
<host>://<uri_root>/<container>/<object>
----

With virtual host set to true, request URIs are of the form:

[source, json]
----
<container>.<host>://<object>
----

NOTE: When virtual host is enabled, the _uri_root_ configuration is ignored.

=== Container
Container is the logical bucket that the OG load tool will write objects into.
OG supports single and multiple container configurations. For multiple
containers, OG supports selection of a container for a given request via round
robin or random configurations. With multiple containers, _prefix_,
_min_suffix_ and _max_suffix_, keys are used to produce a range of container
names. Container(s) are configured via the _container_ key.

.Single Container Example
[source, json]
----
"container": "my_container"
----

.Multiple Container Round Robin Example
[source, json]
----
"container": {
  "selection": "roundrobin",
  "prefix": "my_container",
  "min_suffix": 0,
  "max_suffix": 100
}
----

.Multiple Container Random Example
[source, json]
----
"container": {
  "selection": "random",
  "prefix": "my_container",
  "min_suffix": 0,
  "max_suffix": 100
}
----

=== Headers
Custom HTTP request headers can be added to every request that is executed.
Header values can be constant or dynamic. For dynamic header value
configuration, values can be selected via round robin, random, or weighted
random. Headers are configured via the _headers_ key.

.Headers Static Values Example
[source, json]
----
"headers": {
  "x-custom-01": "1000",
  "x-custom-02": "true"
}
----

.Headers Random Dynamic Values Example
[source, json]
----
"headers": {
  "x-custom-01": {
    "selection": "random",
    "choices": ["1000", "2000", "10000"]
  },
  "x-custom-02": "true"
}
----

.Headers Round Robin Dynamic Values Example
[source, json]
----
"headers": {
  "x-custom-01": {
    "selection": "roundrobin",
    "choices": ["1000", "2000", "10000"]
  },
  "x-custom-02": "true"
}
----

.Headers Weighted Random Dynamic Values Example
[source, json]
----
"headers": {
  "x-custom-01": {
    "selection": "random",
    "choices": [
      {"choice": "1000", "weight": 20.0},
      {"choice": "2000", "weight": 75.0},
      {"choice": "10000", "weight": 5.0}
    ]
  },
  "x-custom-02": "true"
}
----

=== Write, Read, Delete Operations
Write, Read, and Delete operations are supported for all Object Storage APIs.
Operation mix is configured via _write_, _read_, and _delete_ keys,
respectively.

Each operation type is configured via a configuration block. E.g. for write:

[source, json]
----
"write": {}
----

The configuration block supports _weight_, _host_, _object_, and _header_ keys.

==== Operation Weight
The _weight_ configuration key determines what percentage of requests are of
each operation type.

.100% Write Example
[source, json]
----
"write": {"weight": 100.0},
"read": {"weight": 0.0},
"delete": {"weight": 0.0}
----

==== Operation Host
OG supports overriding the global host configuration for a particular operation
type. See <<Host>> for more details.

==== Operation Object
OG supports multiple object name configurations via the _object_ key:

[source, json]
----
"object": {}
----

By default, OG will generate a unique, uuid-like object name for every Write
request. Read and Delete requests will select a random object name from objects
which have already been written. See <<Object Manager>>.

To override this behavior, the _object_ configuration block can be configured
to include _selection_, _prefix_, _min_suffix_, and _max_suffix_ keys. Random
and round robin selection configuration is supported. The resulting object name
will be of the form:

[source, bash]
----
<prefix><suffix>
----

WARNING: Using custom object name configuration bypasses object management.
Object names written with a custom prefix and suffix will not be stored in the
object manager, for example.

.Round Robin Object Name Example
[source, json]
----
"object": {
  "selection": "roundrobin",
  "prefix": "my_object",
  "min_suffix": 0,
  "max_suffix": 100
}
----

==== Operation Headers
OG supports overriding the global headers configuration for a particular operation
type. See <<Headers>> for more details.

=== Filesize
OG supports one or more filesize distributions for describing object file
sizes to be written for write requests. If multiple filesize distributions are
configured, round robin, random, and weighted random selection are supported.

Each file size distribution supports _distribution_, _average_, _average_unit_,
_spread_, and _spread_unit_ keys. *uniform* and *normal* distributions are
supported.

For *uniform* distribution, the shape of the distribution is _average_ +/-
spread. For *normal* distribution the shape of the distribution is centered
about _average_, with one standard deviation of _spread_.

Both _average_unit_ and _spread_unit_ support a large number of size units.
See <<Filesize Units>> for details.

.Single Fixed Filesize (10KB) Example
[source, json]
----
"filesize": {"average": 10, "average_unit": "kb"}
----

.Single Filesize Distribution Example
[source, json]
----
"filesize": {
  "distribution": "uniform",
  "average": 10,
  "average_unit": "kb",
  "spread": 2,
  "spread_unit": "kb"
}
----

.Multiple Filesize Distributions Round Robin Example
[source, json]
----
"filesize": {
  "selection": "roundrobin",
  "choices": [
    {
      "distribution": "uniform",
      "average": 10,
      "average_unit": "kb",
      "spread": 2,
      "spread_unit": "kb"
    },
    {
      "distribution": "normal",
      "average": 100,
      "average_unit": "mb"
    }
  ]
}
----

.Multiple Filesize Distributions Weighted Random Example
[source, json]
----
"filesize": {
  "selection": "random",
  "choices": [
    {
      "choice": {
        "distribution": "uniform",
        "average": 10,
        "average_unit": "kb",
        "spread": 2,
        "spread_unit": "kb"
      },
      "weight": 80.0
    },
    {
      "choice": {
        "distribution": "normal",
        "average": 100,
        "average_unit": "mb"
      },
      "weight": 20.0
    }
  ]
}
----

=== Data
Data determines what type of source data is used for write requests. By
default, OG will generate a small, fixed buffer of random data for every write
request, which is returned repeatedly until the length of the object is
satisfied. Optionally, data can be configured to use all zeroes for object
content. Data is configured via the _data_ key; valid options are *random* and
*zeroes*.

.Zeroes Data Example
[source, json]
----
"data": "zeroes"
----

=== Concurrency
Concurrency configuration allows the OG tool to execute requests in parallel.
There are two types of supported concurrency in OG, *threads* and *ops*.
Concurrency is configured via the _concurrency_ key.

[source, json]
----
"concurrency": {}
----

==== Threads Concurrency
Thread testing involves configuring a fixed number of concurrent TCP
connections, each of which will execute requests as quickly as possible. Thread
based testing is good for measuring system capacity.

Thread testing supports _count_, _rampup_, and _rampup_unit_ keys. Rampup
allows a thread based test to build up to a steady connection rate over a
configurable period of time.

.Single Thread Example
[source, json]
----
"concurrency": {
  "type": "threads",
  "count": 1
}
----

.Multiple Threads Example
[source, json]
----
"concurrency": {
  "type": "threads",
  "count": 10
}
----

.Multiple Threads With Rampup Example
[source, json]
----
"concurrency": {
  "type": "threads",
  "count": 10,
  "rampup": 60,
  "rampup_unit": "seconds"
}
----

See <<Time Units>> for supported time units.

==== Request Rate Concurrency
Request Rate concurrency (ops) testing involves configuring a desired request
rate to send requests at. A variable number of TCP connections will be used to
satisfy the configured rate.

Request Rate testing supports _count_, _unit_, _rampup_, and _rampup_unit_
keys. Rampup allows an ops based test to build up to a steady request rate
over a configurable period of time.

.Request Rate (100 op/s) Example
[source, json]
----
"concurrency": {
  "type": "ops",
  "count": 100,
  "unit": "seconds"
}
----

.Request Rate (500 op/minute) With Rampup Example
[source, json]
----
"concurrency": {
  "type": "ops",
  "count": 500,
  "unit": "minutes",
  "rampup": 60,
  "rampup_unit": "seconds"
}
----

See <<Time Units>> for supported time units.

== Results
For each OG test that is run, a timestamped test results directory is created.
An example:

[source, bash]
----
~$ tree log/
log/
└── 2015-06-17_23.56.32 // <1>
    ├── gc.log // <2>
    ├── og.json // <3>
    ├── og.log // <4>
    ├── request.log // <5>
    └── summary.json // <6>
----
<1> parent directory for a test run
<2> jvm gc.log for this test
<3> serialized og.json, including default values; useful for config auditing
<4> application logs
<5> per-request log, including http details
<6> summary statistics

== Appendix

=== Configuration Reference

==== General Configuration
|===
|Parameter|Type|Default

|scheme
|Enum ("http", "https")
|"http"

|host
|String or SelectionConfig<String>
|None; see <<Selection Configuration>>

|port
|Integer
|None

|api
|Enum ("s3", "openstack", "soh", "webdav")
|None

|uri_root
|String
|"/<api>/"

|container
|String or ContainerConfig
|None; see <<Container Configuration>>

|headers
|Object
|{}

|write
|Decimal or OperationConfig
|100.0; see <<Operation Configuration>>

|read
|Decimal or OperationConfig
|0.0; see <<Operation Configuration>>

|delete
|Decimal or OperationConfig
|0.0; see <<Operation Configuration>>

|filesize
|Decimal or SelectionConfig<FilesizeConfig>
|see <<Filesize Configuration>>

|data
|Enum ("random", "zeroes")
|"random"

|concurrency
|ConcurrencyConfig
|see <<Concurrency Configuration>>

|authentication
|AuthenticationConfig
|see <<Authentication Configuration>>

|client
|ClientConfig
|see <<Client Configuration>>

|stopping_conditions
|StoppingConditionsConfig
|see <<Stopping Conditions Configuration>>

|object_manager
|ObjectManagerConfig
|see <<Object Manager Configuration>>

|shutdown_immediate
|Boolean
|true
|===

==== Operation Configuration
|===
|Parameter|Type|Default

|host_selection
|Enum ("random", "roundrobin")
|"roundrobin"

|host
|String or [HostConfig]
|None

|object
|ObjectConfig
|see <<Object Configuration>>

|headers
|Object
|{}

|weight
|Decimal
|1.0
|===

==== Object Configuration
|===
|Parameter|Type|Default

|prefix
|String
|""

|selection
|Enum ("random", "roundrobin")
|"random"

|min_suffix
|Integer
|0

|max_suffix
|Integer
|9223372036854775807
|===

==== Filesize Configuration
|===
|Parameter|Type|Default

|distribution
|Enum ("uniform", "normal", "lognormal")
|"uniform"

|average
|Decimal
|5.0

|average_unit
|Enum (see <<Filesize Units>>)
|"mebibytes"

|spread
|Decimal
|0.0

|spread_unit
|Enum (see <<Filesize Units>>)
|"mebibytes"

|weight
|Decimal
1.0
|===

==== Concurrency Configuration
|===
|Parameter|Type|Default

|type
|Enum ("threads", "ops")
|"threads"

|count
|Decimal
|1.0

|unit
|Enum (see <<Time Units>>)
|"seconds"

|rampup
|Decimal
|0.0

|rampup_unit
|Enum (see <<Time Units>>)
|"seconds"
|===

==== Authentication Configuration
|===
|Parameter|Type|Default

|type
|Enum ("basic", "awsv2", "awsv4")
|"basic"

|username
|String
|None

|password
|String
|None
|===

==== Client Configuration
|===
|Parameter|Type|Default

|connect_timeout
|Integer
|0

|so_timeout
|Integer
|0

|so_reuse_address
|Boolean
|false

|so_linger
|Integer
|-1

|so_keep_alive
|Boolean
|true

|tcp_no_delay
|Boolean
|true

|so_snd_buf
|Integer
|0; "platform default"

|so_rcv_buf
|Integer
|0; "platform default"

|persistent_connections
|Boolean
|true

|validate_after_inactivity
|Integer
|10000; in milliseconds

|max_idle_time
|Integer
|60000; in milliseconds

|chunked_encoding
|Boolean
|false

|expect_continue
|Boolean
|false

|wait_for_continue
|Integer
|3000

|retry_count
|Integer
|0

|request_sent_retry
|Boolean
|true

|write_throughput
|Integer
|0

|read_throughput
|Integer
|0
|===

==== Stopping Conditions Configuration
|===
|Parameter|Type|Default

|operations
|Integer
|0

|runtime
|Decimal
|0.0

|runtime_unit
|Enum (see <<Time Units>>)
|"seconds"

|concurrent_requests
|Integer
|2000

|status_codes
|Object
|{}
|===

==== Object Manager Configuration
|===
|Parameter|Type|Default

|object_file_location
|String
|"./object"

|object_file_name
|String
|"<container>-<api>"

|object_file_max_size
|Integer; in bytes
|100000000 // 100mb

|object_file_persist_frequency
|Integer; in seconds
|1800 // 30 minutes

|object_file_index
|Integer
|None; advanced option
|===

==== Selection Configuration
|===
|Parameter|Type|Default

|selection
|Enum ("random", "roundrobin")
|"random"

|choices
|List<ChoiceConfig>; see <<Choice Configuration>>
|[]
|===

==== Choice Configuration
|===
|Parameter|Type|Default

|choice
|T
|None

|weight
|Decimal
|1.0
|===

=== Filesize Units
|===
|Input|Unit

|"b", "byte", "bytes"
|bytes

|"kb", "kilobyte", "kilobytes"
|kilobytes

|"kib", "kibibyte", "kibibytes"
|kibibytes

|"mb", "megabyte", "megabytes"
|megabytes

|"mib", "mebibyte", "mebibytes"
|mebibytes

|"gb", "gigabyte", "gigabytes"
|gigabytes

|"gib", "gibibyte", "gibibytes"
|gibibytes

|"tb", "terabyte", "terabytes"
|terabytes

|"tib", "tebibyte", "tebibytes"
|tebibytes

|"pb", "petabyte", "petabytes"
|petabytes

|"pib", "pebibyte", "pebibytes"
|pebibytes
|===

=== Time Units
|===
|Input|Unit

|"ns", "nano", "nanosec", "nanosecs", "nanosecond", "nanoseconds"
|nanoseconds

|"micro", "micros", "microsec", "microsecs", "microsecond", "microseconds"
|microseconds

|"ms", "milli", "millis", "millisec", "millisecs", "millisecond", "milliseconds"
|milliseconds

|"s", "sec", "secs", "second", "seconds"
|seconds

|"m", "min", "mins", "minute", "minutes"
|minutes

|"h", "hr", "hrs", "hour", "hours"
|hours

|"d", "day", "days"
|days
|===
