/* Copyright (c) IBM Corporation 2016. All Rights Reserved.
 * Project name: Object Generator
 * This project is licensed under the Apache License 2.0, see LICENSE.
 */

package com.ibm.og.api;


/**
 * An enum for describing an operation type
 * 
 * @since 1.0
 */
public enum Operation {
  ALL, WRITE, OVERWRITE, READ, METADATA, DELETE, MULTI_DELETE, LIST, CONTAINER_LIST, CONTAINER_CREATE,
  MULTIPART_WRITE, MULTIPART_WRITE_INITIATE, MULTIPART_WRITE_PART, MULTIPART_WRITE_COMPLETE, MULTIPART_WRITE_ABORT,
  WRITE_COPY, WRITE_LEGAL_HOLD, DELETE_LEGAL_HOLD, READ_LEGAL_HOLD, EXTEND_RETENTION, OBJECT_RESTORE,
  PUT_CONTAINER_LIFECYCLE, GET_CONTAINER_LIFECYCLE, DELETE_CONTAINER_LIFECYCLE, PUT_CONTAINER_PROTECTION,
  GET_CONTAINER_PROTECTION, PUT_TAGS, DELETE_TAGS, GET_TAGS, LIST_OBJECT_VERSIONS,
  PUT_OBJECT_LOCK_RETENTION, GET_OBJECT_LOCK_RETENTION, PUT_OBJECT_LOCK_LEGAL_HOLD, GET_OBJECT_LOCK_LEGAL_HOLD,
  WRITE_SELECT_OBJECT
}
